dispatch/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('daily/detail', views.DispatchDetailView.as_view()), # 상세배차리스트
    path('monthly/<str:month>', views.MonthlyDispatches.as_view()),
    path('daily/list/<str:date>', views.DailyListDispatches.as_view()), # 일일배차리스트
    path('problem/list/<str:date>', views.ProblemListDispatches.as_view()), # 문제 배차리스트
    path('problem/detail', views.ProblemDispatchDetailView.as_view()), #문제 배차상세
    path('daily/detail/location-history', views.LocationHistory.as_view()),
    path('daily/routine/get-off-work', views.DailyGetOffWorkView.as_view()),
    path('daily/routine/<str:date>', views.DailyRoutineView.as_view()),
    path('daily/<str:date>', views.DailyDispatches.as_view()),
    path('check', views.DriverCheckView.as_view()),
    path('check2', views.DriverCheckView2.as_view()),
    path('connect/check', views.ConnectCheckView.as_view()),
    path('station/check', views.StationCheckView.as_view()),
    path('regularly', views.RegularlyList.as_view()),
    path('regularly/<int:id>', views.RegularlyDetailView.as_view()),
    path('regularly/group', views.RegularlyGroupList.as_view()),
    path('regularly/know', views.RegularlyKnow.as_view()),
    path('regularly/favorite', views.DispatchRegularlyFavoriteView.as_view()), # 배차 즐겨찾기 생성, 삭제
    path('checklist/morning/<str:date>', views.MorningChecklistView.as_view()),
    path('checklist/evening/<str:date>', views.EveningChecklistView.as_view()),
    path('drivinghistory', views.DrivingHistoryView.as_view()),
    path('driving-history', views.NewDrivingHistoryView.as_view()),
    path('team/list', views.TeamConnectListView.as_view()),
    path('team/<int:id>', views.TeamDriverConnectView.as_view()),
    path('test/reset-connect-check', views.ResetConnectCheck.as_view()),

    # rpa-p
    path('estimate', views.EstimateView.as_view()),
    path('estimate/reservation/confirm', views.EstimateReservationConfirmView.as_view()),
    path('estimate/contract', views.EstimateContract.as_view()),
    path('tour/contract', views.TourContract.as_view()),
    path('tour', views.TourView.as_view()),
    path('send/code', views.send_code), # 전화번호 인증 코드 전송
    path('verify/code', views.verify_code, name='verify_code'), # 전화번호 인증 코드 확인
]

notice/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.NoticeListView.as_view()),
    path('/<int:id>', views.NoticeDetailView.as_view()),
    path('/comment', views.CommentView.as_view()),
    path('/read', views.NoticeAsReadAPIView.as_view()),

    path('/rule/approval/print', views.approval_rule_print, name='approval_rule_print'),
    path('/rule/rollcall/print', views.roll_call_rule_print, name='roll_call_rule_print'),
    path('/rule/driver/print', views.driver_rule_print, name='driver_rule_print'),
    path('/rule/manager/print', views.manager_rule_print, name='manager_rule_print'),
    path('/rule/fieldmanager/print', views.field_manager_rule_print, name='field_manager_rule_print'),
    path('/rule/personnelcommittee/print', views.personnel_committee_rule_print, name='personnel_committee_rule_print'),
    
]

trp_drf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('humanresource.urls')),
    path('dispatch/', include('dispatch.urls')),
    path('complaint/', include('complaint.urls')),
    path('notice', include('notice.urls')),
    path('vehicle', include('vehicle.urls')),
    path('', include('crudmember.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vehicle/models.py
from django.db import models
from django.db.models import F
from crudmember.models import Category
from humanresource.models import Member
from datetime import datetime
from enum import Enum
from uuid import uuid4
from firebase.media_firebase import delete_firebase_file

class Vehicle(models.Model):
    # 차량정보
    vehicle_num0 = models.CharField(verbose_name='차량번호 앞자리', max_length=100, null=False)
    vehicle_num = models.CharField(verbose_name='차량번호', max_length=100, null=False)
    vehicle_id = models.CharField(verbose_name='차대번호', max_length=100, null=False, blank=True)
    motor_type = models.CharField(verbose_name='원동기형식', max_length=100, null=False, blank=True)
    rated_output = models.CharField(verbose_name='정격출력', max_length=100, null=False, blank=True)
    vehicle_type = models.CharField(verbose_name='차량이름', max_length=100, null=False, blank=True)
    maker = models.CharField(verbose_name='제조사', max_length=100, null=False, blank=True)
    model_year = models.CharField(verbose_name='연식', max_length=100, null=False, blank=True)
    release_date = models.CharField(verbose_name='출고일자', max_length=100, null=False, blank=True)
    driver = models.ForeignKey(Member, verbose_name='기사', on_delete=models.SET_NULL, null=True, related_name="vehicle", db_column="vehicle", blank=True)
    use = models.CharField(verbose_name='사용여부', max_length=100, null=False, default='사용', blank=True)
    passenger_num = models.CharField(verbose_name='승차인원', max_length=100, null=False, blank=True)
    check_date = models.CharField(verbose_name='정기점검일', max_length=100, null=False, blank=True)
    type = models.CharField(verbose_name='형식', max_length=100, null=False, blank=True)
    garage = models.ForeignKey("dispatch.Station", on_delete=models.SET_NULL, related_name="garage", verbose_name='차고지', null=True, blank=True)
    remark = models.CharField(verbose_name='비고', max_length=100, null=False, blank=True)

    #차량가격
    vehicle_price = models.IntegerField(verbose_name='차량가격', null=True, blank=True)  # 차량가격
    depreciation_month = models.IntegerField(verbose_name='감가상각(월)', null=True, blank=True)  # 감가상각(월)
    number_price = models.IntegerField(verbose_name='번호판가격', null=True, blank=True)  # 번호판가격
    depreciation_year = models.IntegerField(verbose_name='감가상각 기준 연도', null=True, blank=True)  # 감가상각 기준 연도
    insurance_pay_date = models.CharField(verbose_name='보험납부일', max_length=100, null=True, blank=True)  # 보험납부일
    insurance_price = models.IntegerField(verbose_name='보험비', null=True, blank=True)  # 보험비
    monthly_installment = models.IntegerField(verbose_name='할부금액(월)', null=True, blank=True)  # 할부금액(월)
    remaining_installment_amount = models.IntegerField(verbose_name='남은 할부액', null=True, blank=True)  # 남은 할부액

    #차량옵션
    led = models.BooleanField(verbose_name='전광판유무', default=False)
    fridge = models.BooleanField(verbose_name='냉장고유무', default=False)
    sing = models.BooleanField(verbose_name='노래방유무', default=False)
    usb = models.BooleanField(verbose_name='USB유무', default=False)
    water_heater = models.BooleanField(verbose_name='온수기유무', default=False)
    tv = models.BooleanField(verbose_name='tv유무', default=False)

    # 총 정비 금액
    total_maintenance_cost = models.IntegerField(verbose_name='총정비금액', default=0)
    # 총 튜닝 금액
    total_tuning_cost = models.IntegerField(verbose_name='총튜닝금액', default=0)

    creator = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="vehicle_user", db_column="user_id", null=True)
    pub_date = models.DateTimeField(verbose_name='작성시간', auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정시간')
    
    def count_filled_fields(self):
        """차량 필드 중 값이 채워진 필드의 개수를 계산하고 디버깅 출력"""
        
        fields_to_check = [
            # 차량정보
            self.vehicle_num0,
            self.vehicle_num,
            self.vehicle_id,
            self.motor_type,
            self.rated_output,
            self.vehicle_type,
            self.maker,
            self.model_year,
            self.release_date,
            self.driver,
            # self.use,
            self.passenger_num,
            self.check_date,
            self.type,
            self.garage,
            self.remark,

            # 차량가격
            self.vehicle_price,
            self.depreciation_month,
            self.number_price,
            self.depreciation_year,
            self.insurance_pay_date,
            self.insurance_price,
            self.monthly_installment,
            self.remaining_installment_amount,

            # 차량옵션
            # self.led,
            # self.cold,
            # self.sing,
            # self.usb,
            # self.hot,
            # self.tv,
        ]

        # 값이 있는 필드만 세기 (None과 빈 문자열 제외)
        filled_fields_count = sum(1 for field in fields_to_check if field not in [None, ''])
        
        # 디버깅 출력
        # print("일반 필드 값:")
        # for field in fields_to_check:
        #     print(f"Field: {field}, Is Counted: {field not in [None, '']}")

        return filled_fields_count


    def __str__(self):
        return f'{self.id} / {self.vehicle_num}'

class Maintenance(models.Model):
    MAINTENANCE_CHOICES = [
        ('정비', '정비'),
        ('튜닝', '튜닝'),
        ('점검', '점검')
    ]

    vehicle = models.ForeignKey(Vehicle, on_delete=models.SET_NULL, related_name='maintenance_records', null=True)
    type = models.CharField(verbose_name='구분', max_length=100, choices=MAINTENANCE_CHOICES)
    work_date = models.DateField(verbose_name='작업일자')
    content = models.TextField(verbose_name='작업내용')
    cost = models.IntegerField(verbose_name='비용')

    creator = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="maintenance_creator", db_column="user_id", null=True)
    pub_date = models.DateTimeField(verbose_name='작성시간', auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정시간')

    def save(self, *args, **kwargs):
        if self.vehicle:
            if self.type == '정비':
                # self.vehicle.total_maintenance_cost += self.cost
                self.vehicle.total_maintenance_cost = F('total_maintenance_cost') + self.cost
            elif self.type == '튜닝':
                # self.vehicle.total_tuning_cost += self.cost
                self.vehicle.total_tuning_cost = F('total_tuning_cost') + self.cost
            self.vehicle.save()

        # super() 호출하여 실제 저장 처리
        super().save(*args, **kwargs)


class DocumentType(Enum):
    VEHICLE_REGISTRATION_CERTIFICATE = '차량등록증'
    VEHICLE_FUNCTIONAL_DIAGNOSIS = '자동차기능종합진단서'
    VEHICLE_INSURANCE = '차량보험'
    VEHICLE_INSTALLMENT = '차량할부'

    @classmethod
    def choices(cls):
        return [(key.value, key.value) for key in cls]

class VehicleDocument(models.Model):
    def get_file_path(instance, filename):
        
        ymd_path = datetime.now().strftime('%Y/%m/%d')
        uuid_name = uuid4().hex
        return '/'.join(['vehicle/document', uuid_name])

    vehicle_id = models.ForeignKey(Vehicle, on_delete=models.CASCADE,related_name="vehicle_file", db_column="vehicle_id", null=False)
    file = models.FileField(upload_to=get_file_path, blank=True, null=True)
    filename = models.TextField(null=True, verbose_name='첨부파일명')
    path = models.TextField(null=True, verbose_name='경로')
    type = models.CharField(max_length=30, verbose_name='종류', choices=DocumentType.choices())
    creator = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="vehicle_document_user", db_column="user_id", null=True)
    pub_date = models.DateTimeField(verbose_name='작성시간', auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정시간')

    def delete(self, *args, **kwargs):
        # firebase에서 파일 삭제
        delete_firebase_file(self.path)
        super().delete(*args, **kwargs)
        
class VehiclePhoto(models.Model):
    PHOTO_TYPE_CHOICES = [
        ('차량 앞', '차량 앞'),
        ('차량 뒤', '차량 뒤'),
        ('차량 옆', '차량 옆')
    ]

    def get_file_path(instance, filename):
        uuid_name = uuid4().hex
        return '/'.join(['vehicle/photo', uuid_name])
    
    driver = models.ForeignKey(Member, on_delete=models.SET_NULL, null=True, related_name="vehicle_photo",)
    date = models.CharField(max_length=30, verbose_name='날짜')
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, related_name="vehicle_photo", db_column="vehicle_id", null=False)
    file = models.FileField(upload_to=get_file_path, blank=True, null=True)
    filename = models.TextField(null=True, verbose_name='첨부파일명')
    path = models.TextField(null=True, verbose_name='경로')
    type = models.CharField(max_length=30, verbose_name='종류', choices=PHOTO_TYPE_CHOICES)
    creator = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="vehicle_photo_user", db_column="user_id", null=True)
    pub_date = models.DateTimeField(verbose_name='작성시간', auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정시간')

    def delete(self, *args, **kwargs):
        # firebase에서 파일 삭제
        delete_firebase_file(self.path)
        super().delete(*args, **kwargs)

class Refueling(models.Model):
    refueling_date = models.CharField(verbose_name='주유일', max_length=100, null=False)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.SET_NULL, related_name="vehicle_refueling", null=True)
    driver = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="driver_refueling", null=True)
    km = models.CharField(verbose_name='주유 시 km', max_length=100, null=False)
    refueling_amount = models.CharField(verbose_name='주유량', max_length=100, null=False)
    urea_solution = models.CharField(verbose_name='요소수 L', max_length=100, null=False)
    gas_station = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name="gas_station", null=True)

dispatch/templates/tour_print.html
{% load custom_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="http://34.121.50.23/static/css/dispatch/estimatePrint.css?v=0.1" type="text/css" />
    <link rel="stylesheet" href="http://34.121.50.23/static/css/dispatch/contractPrint.css?v=0.1" type="text/css" />
    <title>Document</title>
</head>

<body>
    <div class="page2">
        <h1 class="center title">계 약 서</h1>
        <p class="margin08">
            본 계약서는 전세버스를 이용하는 고객과 제공자 간의 계약 사항을 명확히 규정하기 위하여 작성되었으며, 갑 ({{customer}})과 을 (전세버스 제공자)는 아래와 같이 계약을 체결한다.
        </p>

        <table class="table2">
            <colgroup>
                <col style="width: 5%;">
                <col style="width: 10%;">
                <col style="width: 20%;">

                <col style="width: 5%;">
                <col style="width: 10%;">
                <col style="width: 20%;">
                <col style="width: 10%;">
                <col style="width: 20%;">
            </colgroup>
            <tr>
                <td rowspan="5" class="center">갑</td>
                <td class="center">등 록 번 호</td>
                <td>135-81-63601</td>
                <td rowspan="5" class="center">을</td>
                <td class="center">등 록 번 호</td>
                <td colspan="3">135-81-63601</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td class="center">상 표</td>
                <td colspan="3">수원시 권선구 매송고색로 804번길 224-46(고색동)</td>
            </tr>
            <tr>
                <td class="center">이 름</td>
                <td>{{customer}}</td>
                <td class="center">상 호</td>
                <td>오랜친구같은여행사</td>
                <td class="center">담 당 자</td>
                <td>이세명</td>
            </tr>
            <tr>
                <td class="center">전 화 번 호</td>
                <td>{{customer_phone}}</td>
                <td class="center">업 체</td>
                <td>오랜친구같은여행사</td>
                <td class="center">종 목</td>
                <td>국내외여행업</td>
            </tr>
            <tr>
                <td class="center">계 좌 번 호</td>
                <td>{{bank}}</td>
                <td class="center">전 화 번 호</td>
                <td>1522-9821</td>
                <td class="center">F A X</td>
                <td>031-295-7151</td>
            </tr>
        </table>

        <h2 class="sub-title">제2조 계약 목적</h2>
        <p class="margin08">
            본 계약은 전세버스 서비스 제공에 관한 제반 사항을 규정함을 목적으로 한다. 을은 갑이 요청한 일정 및 경로에 따라 버스 대절 서비스를 제공하며, 갑은 이에 대한 대금을 지급한다.
        </p>

        <table class="table2">
            <colgroup>
                <col style="width: 5%;">
                <col style="width: 10%;">
                <col style="width: 20%;">

                <col style="width: 5%;">
                <col style="width: 13%;">
                <col style="width: 17%;">
                <col style="width: 13%;">
                <col style="width: 17%;">
            </colgroup>
            <tr>
                <td rowspan="5" class="center">운<br>행<br>일<br>정</td>
                <td class="center">출 발 일</td>
                <td>{{departure_date|slice:10}}</td>
                <td rowspan="5" class="center">차<br>량</td>
                <td class="center">구 분</td>
                <td colspan="3">{{bus_type}}</td>
            </tr>
            <tr>
                <td class="center">도 착 일</td>
                <td>{{arrival_date|slice:10}}</td>
                <td class="center">차 량 번 호</td>
                <td colspan="3">{% for vehicle in vehicle_list %}{{vehicle}} {% endfor %}</td>
            </tr>
            <tr>
                <td class="center">출 발 지</td>
                <td>{{departure}}</td>
                <td class="center">대 수</td>
                <td>{{bus_cnt}}</td>
                <td class="center">인 승</td>
                <td></td>
            </tr>
            <tr>
                <td class="center">경 유 지</td>
                <td>
                    <div class="stationDiv">
                        {% for station in station_list %}{{station}}<br>{% endfor %}
                    </div>
                </td>
                <td class="center">대당 대절료</td>
                <td>{{price}}</td>
                <td class="center">1인당 회비</td>
                <td>{{price_per_person}}</td>
            </tr>
            <tr>
                <td class="center">도 착 지</td>
                <td>{{arrival}}</td>
                <td class="center">총 합</td>
                <td colspan="3">{{total_price}}</td>
            </tr>
        </table>

        <h2 class="sub-title">제3조 서비스 내용</h2>
        <ul class="ul">
            <li>운행 정보 및 세부사항</li>
            <ul class="ul">
                <li>출발지에서 목적지까지의 구체적인 경로는 갑과 을이 사전 협의한 경로를 따른다. 특별한 상황에 따라 경로 변경이 있을 수 있으며, 경로 변경 시 상호 협의 후 결정한다.</li>

            </ul>
        </ul>

        <h2 class="sub-title">제4조 계약 금액 및 지급 방법</h2>
        <ul class="ul">
            <li>지급일 및 지급 방법</li>
            <ul class="ul">
                <li>갑은 을에게 운행일 3일 전까지 계약 금액을 을의 지정 계좌로 입금하여야 한다.</li>
                <li>을의 계좌번호: [IBK기업] 331-011771-01-011</li>
                <li>예금주: 김형주</li>
            </ul>
        </ul>

        <table class="payment-table">
            <tr>
                <td rowspan="3" class="col-small-small center">예<br>약<br>금</td>
                <td class="col-small center">지 불 액</td>
                <td class="col-medium">{{price_per_person}}</td>
                <td rowspan="3" class="col-small-small center">중<br>도<br>금</td>
                <td class="col-small center">지 불 액</td>
                <td class="price col-medium"></td>
            </tr>
            <tr>
                <td class="col-small center">잔 금</td>
                <td class="col-medium">0</td>
                <td class="col-small center">잔 금</td>
                <td class="price col-medium"></td>
            </tr>
            <tr>
                <td class="col-small center">적 요</td>
                <td class="col-medium"></td>
                <td class="col-small center">적 요</td>
                <td class="col-medium"></td>
            </tr>
        </table>
    </div>
    <div class="page2">
        <h2>제5조 계약의 변경 및 취소</h2>
        <ul class="ul">
            <li>갑 또는 을은 계약 변경 사항이 있을 시 상대방과 협의하여 계약 내용을 변경할 수 있다.</li>
            <li>운행일 기준 7일 전까지 취소할 경우 전액 환불, 운행일 기준 3일 전까지 취소할 경우 50% 환불, 운행일 기준 2일 이내 취소 시 환불이 불가하다.</li>
        </ul>

        <h2>제6조 을의 의무</h2>
        <ul class="ul">
            <li>을은 계약된 일정과 경로에 따라 전세버스 운행 서비스를 제공해야 하며, 차량 상태 및 안전 점검을 완료한 후 운행을 시작해야 한다.</li>
            <li>을은 운전기사를 포함한 서비스 제공자의 법적, 안전적 책임을 성실히 이행해야 한다.</li>
        </ul>

        <h2>제7조 갑의 의무</h2>
        <ul class="ul">
            <li>갑은 운행 중 차량 및 운전기사의 안전에 유의해야 하며, 차량 내에서의 질서 유지에 협조해야 한다.</li>
            <li>갑이 임의로 계약 내용을 변경하거나 을의 지시를 따르지 않을 경우, 갑에게 발생한 손해에 대한 책임은 갑에게 있다.</li>
        </ul>

        <h2>제8조 계약 해지</h2>
        <ul class="ul">
            <li>다음의 경우 갑 또는 을은 서면 통지 후 계약을 해지할 수 있다.</li>
            <ul class="ul">
                <li>갑 또는 을이 계약 조건을 위반하거나 이행하지 않는 경우</li>
                <li>천재지변 등 불가항력적인 사유로 인하여 운행이 불가능할 경우</li>
            </ul>
        </ul>

        <h2>제9조 손해배상</h2>
        <ul class="ul">
            <li>을의 귀책사유로 인해 운행이 지연되거나 취소된 경우, 을은 갑에게 전액 환불 또는 손해를 배상해야 한다.</li>
            <li>갑의 귀책사유로 인해 운행이 지연되거나 취소된 경우, 을은 이에 대해 손해배상 청구를 할 수 있다.</li>
        </ul>

        <h2>제10조 기타사항</h2>
        <ul class="ul">
            <li>본 계약서에 명시되지 않은 사항은 상호 협의하여 결정하며, 협의가 이루어지지 않을 경우 대한민국 관련 법령에 따른다.</li>
            <li>갑과 을은 상호 신의성실의 원칙에 따라 본 계약을 성실히 이행하여야 한다.</li>
        </ul>

        <h2>제11조 관할 법원</h2>
        <ul class="ul">
            <li>본 계약과 관련하여 발생하는 분쟁에 대해서는 [갑의 주소지] 관할 법원에서 심리, 판결한다.</li>
            <li>본 계약은 갑과 을이 서명함으로써 효력이 발생하며, 계약 당사자는 본 계약의 내용에 대하여 성실히 이행할 것을 확인한다.</li>
        </ul>
        <br>
        <br>
        <p class="margin08">위와 같은 조건으로 전세버스 운송약관에 의거 계약을 체결합니다.</p>
        <br>
        <p class="date margin08">{{contract_date}}</p>

        <div class="signature-section">
            <div>갑:&nbsp;<span class="blue">[ 고객 서명 ]</span></div>
            <div>을: [ 회사 서명 ]</div>
        </div>
        <br>
        <p class="center margin08">이 계약서는 쌍방의 서명과 날인으로 효력이 발생하며, 갑과 을 각각 1부씩 보관합니다.</p>
    </div>
</body>

</html>