humanresource/urls.py
from django.urls import path

from rest_framework_simplejwt import views as jwt_views
from . import views


urlpatterns = [
    path('login', views.UserLoginView.as_view()),
    # path('drivers/login/', views.DriverLoginView.as_view()),
    # path('companys/login/', views.CompanyLoginView.as_view()),
    path('notification', views.Notification.as_view()),
    path('maintenance', views.MaintenanceView.as_view()),
    path('member/list', views.MemberListView.as_view()),
    path('member', views.LoginMemberView.as_view()),
    path('member/notification/list', views.NotificationListView.as_view(), name="notification_list"), # 알림 조회 API
    path('member/notification/read', views.NotificationUpdateView.as_view(), name='notification_read'), # 알림 읽음 여부 API
    path('member/accident', views.AccidentReportView.as_view()),
    path('salary/detail', views.salary_detail, name='salary_detail'),
    # path('token/obtain', jwt_views.TokenObtainPairView.as_view(), name='token_create'),  # override sjwt stock token
    #path('logout', jwt_views.TokenBlacklistView.as_view(), name='logout'),
    path('token/refresh', views.TokenRefreshView.as_view(), name='token_refresh'),
    path('user/notification/list', views.NotificationListView.as_view(), name="notification_list"), # 알림 조회 API
    path('user/notification/read', views.NotificationUpdateView.as_view(), name='notification_read'), # 알림 읽음 여부 API
    # path('userinfo/name', views.userNamereturnView),
]

notice/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.NoticeListView.as_view()),
    path('/<int:id>', views.NoticeDetailView.as_view()),
    path('/comment', views.CommentView.as_view()),
    path('/read', views.NoticeAsReadAPIView.as_view()),

    path('/rule/approval/print', views.approval_rule_print, name='approval_rule_print'),
    path('/rule/rollcall/print', views.roll_call_rule_print, name='roll_call_rule_print'),
    path('/rule/driver/print', views.driver_rule_print, name='driver_rule_print'),
    path('/rule/manager/print', views.manager_rule_print, name='manager_rule_print'),
    path('/rule/fieldmanager/print', views.field_manager_rule_print, name='field_manager_rule_print'),
    path('/rule/personnelcommittee/print', views.personnel_committee_rule_print, name='personnel_committee_rule_print'),
    
]

trp_drf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('humanresource.urls')),
    path('dispatch/', include('dispatch.urls')),
    path('complaint/', include('complaint.urls')),
    path('notice', include('notice.urls')),
    path('vehicle', include('vehicle.urls')),
    path('', include('crudmember.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

humanresource/models.py
from uuid import uuid4
from django.db import models
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from common.constant import TODAY, WEEK, FORMAT
from django.apps import apps
from salary.selectors import SalarySelector
from salary.models import HourlyWage
from django.core.exceptions import ValidationError

class Team(models.Model):
    name =models.CharField(verbose_name='팀이름', max_length=100, null=False, blank=False)
    pub_date = models.DateTimeField(verbose_name='작성시간', auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정시간')

    def __str__(self):
        return self.name
    
class Member(models.Model):
    username = None
    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = []
    is_anonymous = False
    is_authenticated = True
    is_active = True

    user_id = models.CharField(max_length=100, verbose_name='사용자id', null=True, blank=True)
    password = models.TextField(verbose_name='비밀번호', null=False, blank=True)
    name = models.CharField(verbose_name='이름', max_length=100, null=False)
    role = models.CharField(verbose_name='업무', max_length=100, null=False)
    birthdate = models.CharField(verbose_name='생년월일', max_length=100, null=False, blank=True)
    resident_number1 = models.CharField(verbose_name='주민등록번호 앞자리', max_length=100, null=False, blank=True)
    resident_number2 = models.CharField(verbose_name='주민등록번호 뒷자리', max_length=100, null=False, blank=True)
    phone_num = models.CharField(verbose_name='전화번호', max_length=100, null=False)
    emergency = models.CharField(verbose_name='비상연락망', max_length=100, null=False, blank=True)
    address = models.CharField(verbose_name='주소', max_length=100, null=False)
    entering_date = models.CharField(verbose_name='입사일', max_length=100, null=False)
    note = models.CharField(verbose_name='비고', max_length=100, null=False, blank=True)
    interview_date = models.CharField(verbose_name='면접일', max_length=100, null=False, blank=True)
    contract_date = models.CharField(verbose_name='계약일', max_length=100, null=False, blank=True)
    contract_renewal_date = models.CharField(verbose_name='근로계약갱신일', max_length=100, null=False, blank=True)
    contract_condition = models.CharField(verbose_name='근로계약조건', max_length=100, null=False, blank=True)
    renewal_reason = models.CharField(verbose_name='갱신사유', max_length=100, null=False, blank=True)
    apply_path = models.CharField(verbose_name='지원경로', max_length=100, null=False, blank=True)
    career = models.CharField(verbose_name='경력사항', max_length=100, null=False, blank=True)
    position = models.CharField(verbose_name='직급', max_length=100, null=False, blank=True)
    apprenticeship_note = models.CharField(verbose_name='견습노선 및 내용', max_length=100, null=False, blank=True)
    leave_reason = models.CharField(verbose_name='퇴사사유', max_length=100, null=False, blank=True)
    company = models.CharField(verbose_name='소속회사', max_length=100, null=False, blank=True)
    team = models.ForeignKey(Team, on_delete=models.SET_NULL, related_name="member_team", null=True)
    final_opinion = models.CharField(verbose_name='최종소견', max_length=100, null=False, blank=True)
    interviewer = models.CharField(verbose_name='면접담당자', max_length=100, null=False, blank=True)
    end_date = models.CharField(verbose_name='종료일', max_length=100, null=False, blank=True)
    leave_date = models.CharField(verbose_name='퇴사일', max_length=100, null=False, blank=True)
    allowance_type = models.CharField(verbose_name='수당지급기준', max_length=100, null=False, blank=True, default="기사수당(현재)")
    license = models.CharField(verbose_name='버스기사자격증', max_length=100, null=False, blank=True)
    can_parking_outside = models.BooleanField(verbose_name='외부주차가능여부', null=False, default=False)

    base = models.CharField(verbose_name='기본급', max_length=20, null=False, default=0)
    service_allowance = models.CharField(verbose_name='근속수당', max_length=20, null=False, default=0)
    annual_allowance = models.CharField(verbose_name='연차수당', max_length=20, null=False, default=0)
    performance_allowance = models.CharField(verbose_name='성과급', max_length=20, null=False, default=0)
    overtime_allowance = models.CharField(verbose_name='근로추가수당', max_length=20, null=False, default=0)
    meal = models.CharField(verbose_name='식대', max_length=20, null=False, default=0)
    
    new_annual_allowance = models.CharField(verbose_name="연차수당2", max_length=100, null=False, default=0)
    team_leader_allowance_roll_call = models.CharField(verbose_name="팀장수당(점호관리)", max_length=100, null=False, default=0)
    team_leader_allowance_vehicle_management = models.CharField(verbose_name="팀장수당(차량관리)", max_length=100, null=False, default=0)
    team_leader_allowance_task_management = models.CharField(verbose_name="팀장수당(업무관리)", max_length=100, null=False, default=0)
    full_attendance_allowance = models.CharField(verbose_name="만근수당", max_length=100, null=False, default=0)
    diligence_allowance = models.CharField(verbose_name="성실수당", max_length=100, null=False, default=0)
    accident_free_allowance = models.CharField(verbose_name="무사고수당", max_length=100, null=False, default=0)
    welfare_meal_allowance = models.CharField(verbose_name="복리후생 (식대)", max_length=100, null=False, default=0)
    welfare_fuel_allowance = models.CharField(verbose_name="복리후생(유류비)", max_length=100, null=False, default=0)
    
    pub_date = models.DateTimeField(verbose_name="등록날짜", auto_now_add=True, null=False)
    creator = models.CharField(verbose_name='작성자 이름', max_length=100, null=False, blank=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정시간')
    token = models.CharField(verbose_name='fcmtoken', max_length=500, null=False, blank=True)
    authority = models.IntegerField(verbose_name='권한', null=False, default=4) # 0=최고관리자, 1=관리자, 3=팀장, 4=기사
    use = models.CharField(verbose_name='사용여부', max_length=30, null=False, default='사용')
    def __str__(self):
        return self.name


class MemberFile(models.Model):
    def get_file_path(instance, filename):
    
        ymd_path = datetime.now().strftime('%Y/%m/%d')
        uuid_name = uuid4().hex
        return '/'.join(['humanresource/', ymd_path, uuid_name])

    member_id = models.ForeignKey(Member, on_delete=models.CASCADE, related_name="member_file", db_column="member_id", null=False)
    file = models.FileField(upload_to=get_file_path, null=False)
    filename = models.TextField(null=True, verbose_name='첨부파일명')
    path = models.TextField(null=True, verbose_name='경로')
    type = models.CharField(max_length=100, null=False, verbose_name='면허증, 버스운전자격증')
    creator = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="member_file_user", db_column="user_id", null=True)
    pub_date = models.DateTimeField(verbose_name='작성시간', auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정시간')
    def __str__(self):
        return self.member_id.name + "_" + self.filename

# class HR(models.Model):
#     member_id = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="hr_member", null=True)
#     hr_type = models.CharField(verbose_name="종류", max_length=30, null=False)
#     reason = models.CharField(verbose_name="내용", max_length=100, null=False)
#     start_date = models.CharField(verbose_name="시작날짜", max_length=10,  null=False)
#     end_date = models.CharField(verbose_name="종료날짜", max_length=10,  null=False)
#     pub_date = models.DateTimeField(verbose_name="등록날짜", auto_now_add=True, null=False)
#     creator = models.ForeignKey(Member, on_delete=models.CASCADE, related_name="hr_creator", db_column="creator_id", null=True)

# class Yearly(models.Model):
#     member_id = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="yearly_member", null=True)
#     year = models.CharField(verbose_name="년도", max_length=4, null=False)
#     cnt = models.CharField(verbose_name="연차 사용 개수", max_length=10, null=False)
#     creator = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="yearly_creator", db_column="user_id", null=True)
#     pub_date = models.DateTimeField(verbose_name='작성시간', auto_now_add=True, null=False)
#     def __str__(self):
#         return self.member_id.name

class Department(models.Model):
    name = models.CharField(verbose_name='부서 이름', max_length=50, null=False, unique=True)

    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='작성시간')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정시간')
    creator = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="department_creator", db_column="creator_id", null=True)


class Notification(models.Model):
    CATEGORY_CHOCIES = [
        ('문제발생', '문제발생'),
        ('일정', '일정'),
    ]

    member_id = models.ForeignKey(Member, on_delete=models.CASCADE, related_name="notification", null=False)
    title = models.CharField(verbose_name='제목', max_length=100, null=False)
    content = models.CharField(verbose_name='내용', max_length=100, null=False)
    is_read = models.BooleanField(verbose_name='확인 여부', null=False, default=False)
    category = models.CharField(verbose_name='종류', max_length=100, null=False, choices=CATEGORY_CHOCIES)
    send_datetime = models.CharField(verbose_name='', max_length=19, null=False)
    creator = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name="notification_creator", db_column="user_id", null=True)
    pub_date = models.DateTimeField(verbose_name='작성시간', auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정시간')

    def clean(self):
        # `yyyy-MM-dd HH:mm:ss` 형식 확인
        try:
            datetime.strptime(self.send_datetime, '%Y-%m-%d %H:%M:%S')
        except ValueError:
            raise ValidationError("send_datetime must be in 'yyyy-MM-dd HH:mm:ss' format.")

class Salary(models.Model):
    def set_new_annual_allowance(month, member):

humanresource/templates/salary_detail.html
{% load custom_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>TRP</title>
    <link href="http://34.121.50.23/static/css/humanresource/print.css" rel="stylesheet" type="text/css" />
</head>

<body>
    {% for data in member_list %}
    <div class="salaryStatus">
        <div class="salaryStatusTitle">{{month|slice:':4'}}년 {{month|slice:'5:7'}}월 급여현황</div>

        <div class="signBox">
            <span>{{data.member.name}}</span>
            <span>(서명)</span>
        </div>

        <table class="personalInformationTable">
            <colgroup>
                <col style="width: 7%">
                <col style="width: 8%">
                <col style="width: 23%">
                <col style="width: 8%">
                <col style="width: 23%">
                <col style="width: 8%">
                <col style="width: 23%">
            </colgroup>
            <tr>
                <td rowspan="2" class="titleTd">
                    인적<br>
                    사항
                </td>
                <td class="titleTd">회사명</td>
                <td>성화투어</td>
                <td class="titleTd">성명</td>
                <td>{{data.member.name}}</td>
                <td class="titleTd">생년월일</td>
                <td>{{data.member.birthdate}}</td>
            </tr>
            <tr>
                <td class="titleTd">직급</td>
                <td>{{data.member.role}}</td>
                <td class="titleTd">입사일</td>
                <td>{{data.member.entering_date}}</td>
                <td class="titleTd">지급일</td>
                <td>{{data.salary_date}}</td>
            </tr>
        </table>

        <table class="dateListTable">
            <colgroup>
                <col style="width: 5%">
                <col style="width: 23%">
                <col style="width: 6%">
                <col style="width: 23%">
                <col style="width: 6%">
                <col style="width: 23%">
                <col style="width: 6%">
                <col style="width: 8%">
            </colgroup>
            <thead>
                <tr>
                    <td>일자</td>
                    <td>출근운행</td>
                    <td>출근수당</td>
                    <td>퇴근운행</td>
                    <td>퇴근수당</td>
                    <td>일반운행</td>
                    <td>일반수당</td>
                    <td>일일합계</td>
                </tr>
            </thead>
            <tbody>
                {% for i in data.order_list %}
                <tr>
                    <td>{{forloop.counter}}{{data.week_list|index:forloop.counter0}}</td>
                    <td title="{{data.attendance_list|index:forloop.counter0}}">
                        {% for d in data.attendance_list|index:forloop.counter0 %}
                            {{d.0|slice:':4'}}. {{d.1|slice:':4'}}/
                        {% endfor %}
                    </td>
                    <td class="printComma">
                        {% if data.attendance_list|index:forloop.counter0 %}
                            {{data.attendance_price_list|index:forloop.counter0}}
                        {% endif %}
                    </td>
                    <!-- <td>기흥기숙.마북동 /</td> -->
                    <td title="{{data.leave_list|index:forloop.counter0}}">
                        {% for d in data.leave_list|index:forloop.counter0 %}
                            {{d.0|slice:':4'}}. {{d.1|slice:':4'}}/
                        {% endfor %}
                    </td>
                    <td class="printComma">
                        {% if data.leave_list|index:forloop.counter0 %}
                            {{data.leave_price_list|index:forloop.counter0}}
                        {% endif %}
                    </td>
                    <!-- <td>
                        화성금곡.국립중앙/     화성금곡.국립중앙/<br>
                        화성금곡.국립중앙/
                    </td> -->
                    <td title="{{data.order_list|index:forloop.counter0}}">
                        {% for d in data.order_list|index:forloop.counter0 %}
                            {{d|index:0|slice:':4'}}. {{d|index:1|slice:':4'}} /
                        {% endfor %}
                    </td>
                    <td class="printComma">
                        {% if data.order_list|index:forloop.counter0 %}
                            {{data.order_price_list|index:forloop.counter0}}
                        {% endif %}
                    </td>
                    <td class="printComma">
                        {% if data.order_list|index:forloop.counter0 or data.attendance_list|index:forloop.counter0 or data.leave_list|index:forloop.counter0 %}
                            {{data.total_list|index:forloop.counter0}}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                <tr class="workTotal">
                    <td>소계</td>
                    <td colspan="2">{{data.attendance_cnt}}</td>
                    <td colspan="2">{{data.leave_cnt}}</td>
                    <td colspan="2">{{data.order_cnt}}</td>
                    <td>{{data.total_cnt}}</td>
                </tr>
            </tbody>
        </table>

        <div class="moreInforArea">

            <table class="additionalSalaryTable">
                <colgroup>
                    <col style="width: 10%">
                    <col style="width: 90%">
                </colgroup>
                <tr>
                    <td rowspan="2" class="titleTd">
                        추<br>
                        가<br>
                        수<br>
                        당
                    </td>
                    <td class="titleTd">지급사유</td>
                </tr>
                <tr>
                    <td>
                        
                        {% for add in data.additional %}
                            ({{add.price}}){{add.remark}} /
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td rowspan="2" class="titleTd">
                        공<br>
                        제<br>
                    </td>
                    <td class="titleTd">공제사유</td>
                </tr>
                <tr>
                    <td>
                        {% for ded in data.deduction %}
                            ({{ded.price}}){{ded.remark}} /
                        {% endfor %}
                    </td>
                </tr>
            </table>

            <div class="amountBox">

                <table class="allMountTable">
                    <colgroup>
                        <col style="width: 20%">
                        <col style="width: 30%">
                        <col style="width: 20%">
                        <col style="width: 30%">
                    </colgroup>
                    <tr>
                        <td class="titleTd">출근수당</td>
                        <td class="printComma">{{data.salary.attendance}}</td>
                        <td class="titleTd">기본수당</td>
                        <td class="printComma">{{data.salary.base}}</td>
                    </tr>
                    <tr>
                        <td class="titleTd">퇴근수당</td>
                        <td class="printComma">{{data.salary.leave}}</td>
                        <td class="titleTd">근속수당</td>
                        <td class="printComma">{{data.salary.service_allowance}}</td>
                    </tr>
                    <tr>
                        <td class="titleTd">일반수당</td>
                        <td class="printComma">{{data.salary.order}}</td>
                        <td class="titleTd">성과급</td>
                        <td class="printComma">{{data.salary.performance_allowance}}</td>
                    </tr>
                    <tr>
                        <td class="titleTd">추가수당</td>
                        <td class="printComma">{{data.salary.additional}}</td>
                        <td class="titleTd">식대</td>
                        <td class="printComma">{{data.meal}}</td>
                    </tr>
                    <tr>
                        <td class="titleTd">연차수당</td>
                        <td class="printComma">{{data.salary.annual_allowance}}</td>
                        <td class="titleTd">공제</td>
                        <td class="printComma">{{data.salary.deduction}}</td>
                    </tr>
                </table>

                <!-- <table class="totalAmountTable">
                    <colgroup>
                        <col style="width: 20%">
                        <col style="width: 30%">
                        <col style="width: 20%">
                        <col style="width: 30%">
                    </colgroup>
                    <tr>
                        <td class="titleTd">합계</td>
                        <td class="printComma">{{data.salary.total|add:data.salary.deduction}}</td>
                        <td class="titleTd">공제</td>
                        <td class="printComma">{{data.salary.deduction}}</td>
                    </tr>
                </table> -->

                <table class="salaryTable">
                    <colgroup>
                        <col style="width: 20%">
                        <col style="width: 80%">
                    </colgroup>
                    <tr>
                        <td class="titleTd">급여</td>
                        <td class="printComma">{{data.salary.total}}</td>
                    </tr>
                </table>

            </div>
        </div>
        
    </div>
    {% endfor %}



    {% block script %}
    <script>
        const printComma = document.querySelectorAll(".printComma")

        for (i = 0; i < printComma.length; i++){
            printComma[i].innerText = printComma[i].innerText.replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",");
        };  
    </script>
    {% endblock %}
</body>

</html>